export VERSION := next

YYPKG_FILES := http://win-builds.org/yypkg
YYPKG_VERSION := 1.10-alpha1

COREUTILS_VERSION := 8.21
MAKE_VERSION := 4.1
SED_VERSION := 4.2.2
BASH_VERSION := 4.4
PATCH_VERSION := 2.6.1
TAR_VERSION := 1.27.1
LIBARCHIVE_VERSION := 3.1.2
XZ_VERSION := 5.2.1
M4_VERSION := 1.4.17

FINDUTILS_VERSION := 4.4.2
OCAML_VERSION := 4.04.0
OCAMLBUILD_VERSION := 0.9.3
FINDLIB_VERSION := 1.5.5

FILEUTILS_VERSION := 0.4.5
ARCHIVE_VERSION := 2.8.4+2
CRYPTOKIT_VERSION := 1.10
LIBOCAML_VERSION := v2014-08-08
OCAML_EFL_VERSION := 1.13.0

WEB := notk.org:/var/www/win-builds.org

export MIRROR := http://win-builds.org/$(VERSION)/tarballs

-include Makefile.data.local

WIN_BUILDS_SOURCES := $(shell cd $(dir $(lastword $(MAKEFILE_LIST))) && pwd)
PREFIX := $(WIN_BUILDS_SOURCES)/deps/prefix
export PATH := $(PREFIX)/bin:$(PATH)
LD_LIBRARY_PATH := $(PREFIX)/lib:$(LD_LIBRARY_PATH)

BUILD_TRIPLET ?= $(shell ./config.guess)

NUMJOBS ?= -j2
