#!/bin/sh

set -eu

cflags() {
  local dbg
  local hardening
  local optimization

  case "${YYDEFAULTINCLUDEPATH:-""}" in
    no) include_path='' ;;
    *)
      include_path="-I/${PREFIX}/include"
      if [ x"${HOST_TRIPLET:-""}" != x"${TARGET_TRIPLET:-""}" ]; then
        include_path="${include_path} -I${YYPREFIX_NATIVE}/include"
      fi ;;
  esac

  case "${YYOPTIMIZATION:-""}" in
    *) optimization='-O2' ;;
  esac

  case "${YYDEBUG:-""}" in
    3) dbg='-ggdb3' ;;
    2) dbg='-ggdb2' ;;
    1 | *) dbg='-ggdb' ;;
    0) dbg='-ggdb0' ;;
  esac

  case "${YYHARDENING:-""}" in
    *) hardening='' ;;
  esac

  echo ${include_path} ${optimization} ${dbg} ${hardening}
}

cxxflags() {
  cflags "$@"
}

asflags() {
  local dbg

  case "${YYDEBUG:-""}" in
    0) dbg='' ;;
    *) dbg='-g' ;;
  esac

  echo ${dbg}
}

ldflags() {
  local triplet="${1:-"${HOST_TRIPLET}"}"

  local library_path=''
  local hardening=''
  local high_entropy_va=''

  case "${YYDEFAULTLIBRARYPATH:-""}" in
    no) library_path='' ;;
    *)
      library_path="-L/${PREFIX}/lib${LIBDIRSUFFIX}"
      if [ x"${HOST_TRIPLET:-""}" != x"${TARGET_TRIPLET:-""}" ]; then
        library_path="${library_path} -L${YYPREFIX_NATIVE}/lib${LIBDIRSUFFIX}"
      fi ;;
  esac

  case "${triplet}" in
    x86_64-w64-mingw32)
      dynamicbase=',--dynamicbase'
      nxcompat=',--nxcompat'
      high_entropy_va=',--high-entropy-va'
      ;;
    i?86-w64-mingw32)
      dynamicbase=',--dynamicbase'
      nxcompat=',--nxcompat'
      high_entropy_va=''
      ;;
    *)
      dynamicbase=''
      nxcompat=''
      high_entropy_va=''
      ;;
  esac
  case "${YYHARDENING:-""}" in
    no) hardening='' ;;
    *) hardening="${dynamicbase}${nxcompat}${high_entropy_va}" ;;
  esac

  echo ${library_path} ${hardening:+"-Wl${hardening}"}
}

case "${1}" in
  "as") asflags ;;
  "c") cflags ;;
  "cxx") cxxflags ;;
  "ld") ldflags ;;
esac
