#!/bin/sh

set -ex

# Variables below must not come from the environment
unset PKGNAM CWD PKG PACKAGER PACKAGER_MAIL
unset VERSION BUILD HOST_TRIPLET TARGET_TRIPLET

# DESCR is optional
DESCR=""

: ${YYOUTPUT?"must be provided through the environment."}

while [ "$#" -ne 0 ]; do
  case "${1}" in
    --package-name|-p)
      PKGNAM="${2}"
      shift 2
      ;;
    --cwd)
      CWD="${2}"
      shift 2
      ;;
    --pkg)
      PKG="${2}"
      shift 2
      ;;
    --sub)
      SUB="${2}"
      shift 2
      ;;
    --version)
      VERSION="${2}"
      shift 2
      ;;
    --build)
      BUILD="${2}"
      shift 2
      ;;
    --target)
      TARGET_TRIPLET="${2}"
      shift 2
      ;;
    --host)
      HOST_TRIPLET="${2}"
      shift 2
      ;;
    --packager)
      PACKAGER="${2}"
      shift 2
      ;;
    --packager-mail)
      PACKAGER_MAIL="${2}"
      shift 2
      ;;
    --description)
      DESCR="${2}"
      shift 2
      ;;
    --)
      shift 1
      break
      ;;
    -*)
      echo "Unknown option \`${1}'." 1>&2
      exit 1
      ;;
    *)
      if [ -n "${PKGNAM}" ]; then
        echo "Package name already set, ${1} is bogus." 1>&2
        exit 1
      fi
      PKGNAM="${1}"
      shift
      ;;
  esac
done

set -u

if [ -z "${DESCR:-""}" ] && [ -e "${CWD}/slack-desc" ]; then
  DESCR="$(awk "BEGIN { ORS = \" \"; plen = length(\"${PKGNAM}: \"); } /^${PKGNAM}: / { print substr(\$0, 1 + plen, length(\$0) - plen) }" "${CWD}/slack-desc")"
fi

( cat "${PKGNAM}.yypkg.script" 2>/dev/null || yypkg --makepkg --template 'yes' ) \
| awk -f "${WIN_BUILDS_SOURCES}/package_support/yymakepkg.awk" \
  -v "PKG=${PKGNAM}${SUB:+-${SUB}}" \
  -v "HOST_TRIPLET=${HOST_TRIPLET}" \
  -v "TARGET_TRIPLET=${TARGET_TRIPLET:-""}" \
  -v "DESCRIPTION=${DESCR:-"No description"}" \
  -v "VERSION=${VERSION}" \
  -v "BUILD=${BUILD}" \
  -v "PACKAGER=${PACKAGER}" \
  -v "PACKAGER_MAIL=${PACKAGER_MAIL}" \
  -v "PREDICATE_SUB=${SUB:+(${SUB} "yes")}" \
  | yypkg --makepkg --output ${YYOUTPUT} --script - \
      --directory "${PKG}/${PREFIX}" \
      --tar-args -- "$@"
