#!/bin/sh

# We don't use -x because the loop at the bottom of the script iterates over
# hundreds or thousands of files in each package and -x spams a lot.
set -e

: ${PREFIX?"must be provided through the environment."}
: ${LIBDIRSUFFIX?"must be provided through the environment."}

while [ "$#" -ne 0 ]; do
  case "${1}" in
    --pkg)
      PKG="${2}"
      shift 2
      ;;
    -*)
      echo "Unknown option \`${1}'." 1>&2
      exit 1
      ;;
    *)
      echo "Unknown value \`${1}'." 1>&2
      exit 1
      ;;
  esac
done

set -u

# TODO: is it possible to handle static archives?
# TODO: can gnu-debuglink be a relative path?

find "${PKG}/${PREFIX}" -type f -size +4k -exec file {} + \
  | sed "s,^${PKG}/${PREFIX}/,," \
  | while read l; do \
      case "${l}" in
        *\ ELF\ *\ LSB\ executable* | *PE*\ executable*)
          yysplit --pkg "${PKG}" "${l%%:*}" ;;
      esac
done
